import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const script=readFileSync(join(process.cwd(),'js/public-transmissions.js'),'utf8'),styles=readFileSync(join(process.cwd(),'css/public-transmissions.css'),'utf8'),harness='http://127.0.0.1:4173/public-transmissions-e2e.html';
const root={blog:[{id:11,title:'Signal from Genesis',slug:'signal-from-genesis',excerpt:'A report from the floor.',cover_image:'/uploads/genesis-signal.jpg',featured:1,published_at:'2026-09-10 12:00:00',tags:[{name:'Recap'},{name:'Culture'}],relations:[{related_type:'event',related_id:7},{related_type:'artist',related_id:2},{related_type:'release',related_id:999}]},{id:12,title:'Resident Transmission',slug:'resident-transmission',excerpt:'Inside the collective.',cover_image:'',featured:0,published_at:'2026-09-08 12:00:00',tags:[{name:'Residents'}],relations:[{related_type:'artist',related_id:2}]},{id:13,title:'<img id="transmission-xss" src=x onerror="window.__transmissionXss=1">',slug:'hostile-title',excerpt:'<script>window.__transmissionXss=2</script>',cover_image:'javascript:window.__transmissionImageXss=1',featured:0,published_at:'2026-09-05 12:00:00',tags:[],relations:[]}],events:[{id:7,title:'GENESIS',slug:'genesis'}],archive:{events:[]},artists:[{id:2,name:'PL0N3R',slug:'pl0n3r'}],sets:[],releases:[{id:5,title:'BRVTAL 001',slug:'brvtal-001'}]};
function markup(p){return '<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>:root{--line:rgba(255,255,255,.14);--acid:#b8ff00;--ease:cubic-bezier(.16,1,.3,1)}*{box-sizing:border-box}html,body{margin:0;background:#050505;color:#eee;font-family:Arial}.mono{font-family:monospace}'+styles+'</style></head><body><section class="transmissions" id="transmissions"><div class="transmissions-head"><div><span class="transmissions-kicker mono">EDITORIAL SIGNAL / 00</span><h2>TRANSMISSIONS</h2></div><p>Editorial archive.</p></div><div class="transmissions-grid" data-transmissions-grid><article class="transmission transmission-fallback"><h3>STATIC FALLBACK</h3></article></div><div data-transmissions-count></div></section><script>'+p+'</script><script>'+script+'</script></body></html>';}
async function open(page,value=root){await page.route(harness,r=>r.fulfill({contentType:'text/html; charset=utf-8',body:markup('window.BRVTALPublicDataPromise=Promise.resolve({payload:{data:'+JSON.stringify(value)+'}});')}));await page.goto(harness);await expect(page.locator('html')).toHaveAttribute('data-public-transmissions','editorial');}
test('renders canonical Blog records and explicit public relations',async({page})=>{await open(page);const cards=page.locator('[data-transmission-id]');await expect(cards).toHaveCount(3);await expect(cards.nth(0)).toHaveClass(/transmission--featured/);await expect(cards.nth(0).locator('.transmission-title-link')).toHaveAttribute('href','/blog/signal-from-genesis');await expect(cards.nth(0).locator('a[href="/events/genesis"]')).toContainText('EVENT / GENESIS');await expect(cards.nth(0).locator('a[href="/artists/pl0n3r"]')).toContainText('ARTIST / PL0N3R');await expect(cards.nth(0).locator('.transmission-relation')).toHaveCount(2);await expect(cards.nth(0).locator('.transmission-tag')).toHaveText(['RECAP','CULTURE']);await expect(page.locator('[data-transmissions-count]')).toHaveText('03 / 03 TRANSMISSIONS');});
test('hostile strings stay text and unsafe images are rejected',async({page})=>{await open(page);const h=page.locator('[data-transmission-id="13"]');await expect(h.locator('h3')).toHaveText('<img id="transmission-xss" src=x onerror="window.__transmissionXss=1">');await expect(h.locator('.transmission-excerpt')).toHaveText('<script>window.__transmissionXss=2</script>');await expect(h.locator('img')).toHaveCount(0);await expect(page.locator('#transmission-xss')).toHaveCount(0);expect(await page.evaluate(()=>window.__transmissionXss)).toBeUndefined();});
test('mobile is touch-safe without overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await open(page);expect(await page.locator('.transmission-open').first().evaluate(n=>n.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);expect(await page.locator('.transmission-relation').first().evaluate(n=>n.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);const d=await page.evaluate(()=>({v:document.documentElement.clientWidth,s:document.documentElement.scrollWidth}));expect(d.s).toBeLessThanOrEqual(d.v);});
test('valid empty Blog replaces fallback honestly',async({page})=>{await open(page,{blog:[],events:[],archive:{events:[]},artists:[],sets:[],releases:[]});await expect(page.locator('.transmission-fallback')).toHaveCount(0);await expect(page.locator('.transmissions-empty')).toContainText('NO PUBLISHED TRANSMISSIONS YET.');});
test('shared request failure preserves static fallback',async({page})=>{await page.route(harness,r=>r.fulfill({contentType:'text/html; charset=utf-8',body:markup("window.BRVTALPublicDataPromise=new Promise((_,reject)=>setTimeout(()=>reject(new Error('offline')),25));")}));await page.goto(harness);await page.waitForTimeout(350);await expect(page.locator('.transmission-fallback')).toContainText('STATIC FALLBACK');await expect(page.locator('html')).not.toHaveAttribute('data-public-transmissions','editorial');});
