name: Privacy

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  privacy:
    uses: pl0n3r/factory/.github/workflows/privacidad.yml@3341681fcc89bc46e752dd3f8f4093e831578c69
    with:
      kit_ref: 3341681fcc89bc46e752dd3f8f4093e831578c69
