name: Privacy

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  privacy:
    uses: pl0n3r/factory/.github/workflows/privacidad.yml@fd4674c27e4bd54cce1a2d92e6432f845396fa71
    with:
      kit_ref: fd4674c27e4bd54cce1a2d92e6432f845396fa71
