name: Privacy

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  privacy:
    uses: pl0n3r/factory/.github/workflows/privacidad.yml@4b2be9fcf827278631caa3e3e68603b6e2a680d7
    with:
      kit_ref: 4b2be9fcf827278631caa3e3e68603b6e2a680d7
